USE APRILPYTHON;
CREATE TABLE CUSTOMER(CUSTOMER_ID INT PRIMARY KEY, CUSTOMER_NAME VARCHAR(50), CITY VARCHAR(50));
INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, CITY) VALUES (1,'RAHUL','PUNE'),(2,'SNEHA','MUMBAI'),(3,'AMIT','DELHI'),(4,'NEHA','BANGALORE');
SELECT * FROM CUSTOMER;

CREATE TABLE Orders (
    Order_ID INT PRIMARY KEY,
    Customer_ID INT,
    Product VARCHAR(50)
);

INSERT INTO Orders (Order_ID, Customer_ID, Product) VALUES
(101, 1, 'Laptop'),
(102, 2, 'Mobile'),
(103, 2, 'Headphones'),
(104, 5, 'Tablet');
SELECT * FROM ORDERS;

CREATE TABLE PRODUCTS(CUSTOMER_ID INT PRIMARY KEY, PRODUCT_NAME VARCHAR(50),PRICE DECIMAL(10,2));
INSERT INTO PRODUCTS(CUSTOMER_ID, PRODUCT_NAME,PRICE) VALUES (1,'LAPTOP',70000),(2,'MOBILE',25000),(3,'HEADPHONES',3000),(4,'TABLET',20000);
SELECT * FROM PRODUCTS;

-- 1. INNER JOIN:
SELECT * FROM CUSTOMER INNER JOIN ORDERS ON CUSTOMER.CUSTOMER_ID=ORDERS.CUSTOMER_ID;

SELECT C.CUSTOMER_ID, C.CUSTOMER_NAME,C.CITY,O.ORDER_ID,O.PRODUCT
FROM CUSTOMER C INNER JOIN ORDERS O ON 
C.CUSTOMER_ID=O.CUSTOMER_ID;

-- 2. LEFT OUTER JOIN/LEFT JOIN:
SELECT * FROM CUSTOMER C LEFT JOIN ORDERS O ON C.CUSTOMER_ID=O.CUSTOMER_ID;

SELECT C.CUSTOMER_ID, C.CUSTOMER_NAME,C.CITY,O.PRODUCT
FROM CUSTOMER C LEFT JOIN ORDERS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID;

-- 3. RIGHT OUTER JOIN/RIGHT JOIN:
SELECT * FROM CUSTOMER C RIGHT JOIN ORDERS O ON C.CUSTOMER_ID=O.CUSTOMER_ID;

SELECT C.CUSTOMER_ID,C.CUSTOMER_NAME,C.CITY,O.PRODUCT
FROM CUSTOMER C RIGHT JOIN ORDERS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID;

-- 4. FULL OUTER JOIN/FULL JOIN:
SELECT * FROM CUSTOMER C LEFT JOIN ORDERS O ON C.CUSTOMER_ID=O.CUSTOMER_ID
UNION 
SELECT * FROM CUSTOMER C RIGHT JOIN ORDERS O ON C.CUSTOMER_ID=O.CUSTOMER_ID;

SELECT C.CUSTOMER_ID, C.CUSTOMER_NAME,C.CITY,O.PRODUCT
FROM CUSTOMER C LEFT JOIN ORDERS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID
UNION 
SELECT C.CUSTOMER_ID,C.CUSTOMER_NAME,C.CITY,O.PRODUCT
FROM CUSTOMER C RIGHT JOIN ORDERS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID;

-- 5. CROSS JOIN:
SELECT * FROM CUSTOMER CROSS JOIN ORDERS ON CUSTOMER.CUSTOMER_ID=ORDERS.CUSTOMER_ID;

SELECT C.CUSTOMER_ID, C.CUSTOMER_NAME, C.CITY,O.PRODUCT FROM CUSTOMER C CROSS JOIN ORDERS O ON C.CUSTOMER_ID=O.CUSTOMER_ID;


