USE APRILPYTHON;
CREATE TABLE CUSTOMER(CUSTOMER_ID INT PRIMARY KEY, CUSTOMER_NAME VARCHAR(50), CITY VARCHAR(50));
INSERT INTO CUSTOMER (CUSTOMER_ID, CUSTOMER_NAME, CITY) VALUES (1,'RAHUL','PUNE'),(2,'SNEHA','MUMBAI'),(3,'AMIT','DELHI'),(4,'NEHA','BANGALORE');
SELECT * FROM CUSTOMER;

CREATE TABLE Orders (
    Order_ID INT PRIMARY KEY,
    Customer_ID INT,
    Product VARCHAR(50)
);

INSERT INTO Orders (Order_ID, Customer_ID, Product) VALUES
(101, 1, 'Laptop'),
(102, 2, 'Mobile'),
(103, 2, 'Headphones'),
(104, 5, 'Tablet');
SELECT * FROM ORDERS;

CREATE TABLE PRODUCTS(CUSTOMER_ID INT PRIMARY KEY, PRODUCT_NAME VARCHAR(50),PRICE DECIMAL(10,2));
INSERT INTO PRODUCTS(CUSTOMER_ID, PRODUCT_NAME,PRICE) VALUES (1,'LAPTOP',70000),(2,'MOBILE',25000),(3,'HEADPHONES',3000),(4,'TABLET',20000);
SELECT * FROM PRODUCTS;

-- 1. INNER JOIN:
SELECT * FROM CUSTOMER INNER JOIN ORDERS ON CUSTOMER.CUSTOMER_ID=ORDERS.CUSTOMER_ID;

SELECT C.CUSTOMER_ID, C.CUSTOMER_NAME,C.CITY,O.ORDER_ID,O.PRODUCT
FROM CUSTOMER C INNER JOIN ORDERS O ON 
C.CUSTOMER_ID=O.CUSTOMER_ID;

-- 2. LEFT OUTER JOIN/LEFT JOIN:
SELECT * FROM CUSTOMER C LEFT JOIN ORDERS O ON C.CUSTOMER_ID=O.CUSTOMER_ID;

SELECT C.CUSTOMER_ID, C.CUSTOMER_NAME,C.CITY,O.PRODUCT
FROM CUSTOMER C LEFT JOIN ORDERS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID;

-- 3. RIGHT OUTER JOIN/RIGHT JOIN:
SELECT * FROM CUSTOMER C RIGHT JOIN ORDERS O ON C.CUSTOMER_ID=O.CUSTOMER_ID;

SELECT C.CUSTOMER_ID,C.CUSTOMER_NAME,C.CITY,O.PRODUCT
FROM CUSTOMER C RIGHT JOIN ORDERS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID;

-- 4. FULL OUTER JOIN/FULL JOIN:
SELECT * FROM CUSTOMER C LEFT JOIN ORDERS O ON C.CUSTOMER_ID=O.CUSTOMER_ID
UNION 
SELECT * FROM CUSTOMER C RIGHT JOIN ORDERS O ON C.CUSTOMER_ID=O.CUSTOMER_ID;

SELECT C.CUSTOMER_ID, C.CUSTOMER_NAME,C.CITY,O.PRODUCT
FROM CUSTOMER C LEFT JOIN ORDERS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID
UNION 
SELECT C.CUSTOMER_ID,C.CUSTOMER_NAME,C.CITY,O.PRODUCT
FROM CUSTOMER C RIGHT JOIN ORDERS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID;

-- 5. CROSS JOIN:
SELECT * FROM CUSTOMER CROSS JOIN ORDERS ;

SELECT C.CUSTOMER_ID, C.CUSTOMER_NAME, C.CITY,O.PRODUCT FROM CUSTOMER C CROSS JOIN ORDERS O ON C.CUSTOMER_ID=O.CUSTOMER_ID;

-- Join Questions: 
-- 1.Write a query to display Customer Name and Product ordered by them.
SELECT C.CUSTOMER_NAME,O.PRODUCT 
FROM CUSTOMER C INNER JOIN ORDERS O 
ON C.CUSTOMER_ID=O.CUSTOMER_ID;

-- 2.Write a query to display all customers and their products.Customers who have not placed any order should also appear.
SELECT C.CUSTOMER_NAME,O.PRODUCT
FROM CUSTOMER C LEFT JOIN ORDERS O 
ON C.CUSTOMER_ID=O.CUSTOMER_ID;

-- 3.Write a query to display all orders along with customer names, even if the customer details are missing.
SELECT C.CUSTOMER_NAME,O.PRODUCT
FROM CUSTOMER C RIGHT JOIN ORDERS O 
ON C.CUSTOMER_ID=O.CUSTOMER_ID;

-- 4.Write a query to display customers who have not placed any orders.
SELECT C.CUSTOMER_NAME,O.PRODUCT
FROM CUSTOMER C LEFT JOIN ORDERS O 
ON C.CUSTOMER_ID=O.CUSTOMER_ID WHERE O.ORDER_ID IS NULL;

-- 5.Write a query to display customer name and total number of orders placed by each customer.
SELECT C.CUSTOMER_NAME,COUNT(O.ORDER_ID) AS TOTAL_ORDERS
FROM CUSTOMER C LEFT JOIN ORDERS O 
ON C.CUSTOMER_ID=O.CUSTOMER_ID GROUP BY C.CUSTOMER_NAME;

-- 6.Write a query to display Customer Name, City, and Product where the customer is from 'Pune'.
SELECT C.CUSTOMER_NAME,C.CITY,O.PRODUCT
FROM CUSTOMER C LEFT JOIN ORDERS O 
ON C.CUSTOMER_ID=O.CUSTOMER_ID WHERE C.CITY='PUNE';

-- 7.Write a query to display customers who placed more than one order.
SELECT C.CUSTOMER_NAME,COUNT(O.ORDER_ID) AS TOTAL_ORDERS
FROM CUSTOMER C LEFT JOIN ORDERS O 
ON C.CUSTOMER_ID=O.CUSTOMER_ID 
GROUP BY C.CUSTOMER_NAME HAVING COUNT(O.ORDER_ID)>1;

-- 8.Write a query to display Customer Name, City, and Product who order product 'LAPTOP';
 SELECT C.CUSTOMER_NAME,C.CITY,O.PRODUCT 
FROM CUSTOMER C JOIN ORDERS O 
ON C.CUSTOMER_ID=O.CUSTOMER_ID WHERE O.PRODUCT='LAPTOP';

-- 9..Write a query to display Customer Name, City, and Product who order product 'LAPTOP' OR 'MOBILE'.
SELECT C.CUSTOMER_NAME,C.CITY,O.PRODUCT 
FROM CUSTOMER C JOIN ORDERS O 
ON C.CUSTOMER_ID=O.CUSTOMER_ID WHERE O.PRODUCT='LAPTOP' OR O.PRODUCT='MOBILE';

SELECT C.CUSTOMER_NAME,C.CITY,O.PRODUCT 
FROM CUSTOMER C JOIN ORDERS O 
ON C.CUSTOMER_ID=O.CUSTOMER_ID WHERE O.PRODUCT IN ('LAPTOP','MOBILE');

-- (QUESTIONS ON EMPLOYEE AND DEPARTMENT TABLE)
-- 1. Display all employees and their department names.
SELECT E.FIRST_NAME,E.LAST_NAME,D.DEPT_NAME 
FROM EMPLOYEE E LEFT JOIN DEPARTMENT D 
ON E.DEPT_ID=D.DEPT_ID;

-- 2. Display all departments and their employees.
SELECT D.DEPT_NAME,E.FIRST_NAME,E.LAST_NAME 
FROM EMPLOYEE E RIGHT JOIN DEPARTMENT D 
ON E.DEPT_ID=D.DEPT_ID;

-- 3. Display employee name, department name, and hire date.
SELECT E.FIRST_NAME,E.LAST_NAME,D.DEPT_NAME,E.HIRE_DATE
FROM EMPLOYEE E JOIN DEPARTMENT D 
ON E.DEPT_ID=D.DEPT_ID;

-- 4. List employees working in the IT department.
SELECT E.FIRST_NAME,E.LAST_NAME,D.DEPT_NAME
FROM EMPLOYEE E JOIN DEPARTMENT D 
ON E.DEPT_ID=D.DEPT_ID WHERE D.DEPT_NAME='IT';

-- 5. Show employee name, salary, and department location.
SELECT E.FIRST_NAME,E.LAST_NAME,D.LOCATION 
FROM EMPLOYEE E JOIN DEPARTMENT D 
ON E.DEPT_ID=D.DEPT_ID;

-- 6. Display employee first name, last name, and department name.
SELECT E.FIRST_NAME,E.LAST_NAME,D.DEPT_NAME
FROM EMPLOYEE E JOIN DEPARTMENT D 
ON E.DEPT_ID=D.DEPT_ID;
-- CROSS JOIN
SELECT *FROM CUSTOMER;
SELECT * FROM ORDERS;
SELECT * FROM CUSTOMER CROSS JOIN ORDERS;
-- SELFT JOIN
CREATE TABLE Employees1 (
    Emp_ID INT PRIMARY KEY,
    Emp_Name VARCHAR(50),
    Manager_ID INT
);



-- Questions on Employee Table
CREATE TABLE Employees1 (
    Emp_ID INT PRIMARY KEY,
    Emp_Name VARCHAR(50),
    Manager_ID INT
);

INSERT INTO Employees1 (Emp_ID, Emp_Name, Manager_ID) VALUES
(1, 'Rahul', NULL),
(2, 'Sneha', 1),
(3, 'Amit', 1),
(4, 'Neha', 2),
(5, 'Rohan', 2);

select * from Employees1;
SELECT E.EMP_NAME AS EMPLOYEE,M.EMP_NAME AS MANAGER
FROM EMPLOYEES1 E LEFT JOIN EMPLOYEES1 M
ON E.MANAGER_ID=M.EMP_ID;

 