USE APRILPYTHON;
-- FUNCTION
-- PREDEFINE FUNCTION
-- 1.STRING FUNCTION
-- 1.1 CONCAT():
SELECT CONCAT('HELLO',' ','GOOD MORNING');
-- 1.2 LENGTH():
SELECT LENGTH("HELLO WORLD");
-- 1.3 CHAR_LENGTH():
SELECT char_length("HELLO");
-- 1.4 LOWER():
SELECT LOWER("GOOD MORNING");
-- 1.5 UPPER():
SELECT UPPER("GOOD AFTERNOON");
-- 1.6 TRIM():
SELECT TRIM(' HELLO ');
-- 1.7 SUBSTRING():
SELECT SUBSTRING('DATABASE',1,4);
-- 1.8 REVERSE():
SELECT REVERSE("DATA");
-- 1.9 REPLACE():
SELECT REPLACE('20-10-2025','-','/');
-- 1.10 INSTR():
SELECT INSTR("HELLO WORLD",'HELLO');
-- 1.11 RIGHT():
SELECT RIGHT("ABCDRF",5);