USE APRILPYTHON;

-- TRANSACTION
-- TCL(TRANSACTION CONTROL LANGUAGE)
-- 1. COMMIT: SAVE CHANGES PERMANENTLY
-- 2. ROLLBACK: WORK ON UNDO
-- 3. SAVEPOINT: CREATE A CHECKPOINT WITHIN A TRANSACTION. 
                 
-- EX 1:
SET AUTOCOMMIT=0;
SELECT * FROM CUSTOMER;
INSERT INTO CUSTOMER(CUSTOMER_ID, CUSTOMER_NAME, CITY) VALUES
(5, "RAM","PUNE");
COMMIT;
ROLLBACK;

UPDATE CUSTOMER SET CITY="MUMBAI" WHERE CUSTOMER_ID=1;
SAVEPOINT S1;
DELETE FROM CUSTOMER WHERE CUSTOMER_ID=5;
ROLLBACK TO S1;
SAVEPOINT S2;
ROLLBACK TO S2;
ROLLBACK;
COMMIT;

-- EX 2:
SELECT * FROM STUDENT;
INSERT INTO STUDENT(STUDENT_ID, STUDENT_NAME,AGE,COURSE,CITY ) VALUES
(11, "SAI",25,"MCA","MUMBAI");

DELETE FROM STUDENT WHERE STUDENT_ID=1;
SAVEPOINT P1;

UPDATE STUDENT SET AGE=20 WHERE STUDENT_NAME="NEHA";
SAVEPOINT P2;
ROLLBACK TO P1;
ROLLBACK TO P2;
ROLLBACK;
COMMIT;

-- EX 3:
CREATE TABLE S1(SRNO INT, NAME CHAR(10));
INSERT INTO S1(SRNO, NAME) VALUES (1, "SONALI"),(2,"RAM"),
(3,"SHYAM"),(4,"JOHN"),(5,"SONA");
SELECT * FROM S1;
COMMIT;

-- EX 4:
DROP TABLE ACCOUNT;
DROP TABLE TRANSACTIONS;
CREATE TABLE Account (
AccountID INT PRIMARY KEY AUTO_INCREMENT,
AccountHolderName VARCHAR(100) NOT NULL, Balance DECIMAL(10,2) NOT NULL DEFAULT 0.00
);

INSERT INTO Account (AccountHolderName, Balance) 
VALUES
('John', 8000.00),
('Priya', 12000.00),
('Amit', 5000.00);

SELECT * FROM ACCOUNT;

-- TABLE -TRANSACTIONS
CREATE TABLE Transactions (
TransactionID INT PRIMARY KEY AUTO_INCREMENT,
FromAccount INT, ToAccount INT,
Amount DECIMAL(10,2) NOT NULL,
TransactionType ENUM('DEPOSIT', 'WITHDRAW', 'TRANSFER') NOT NULL, 
TransactionDate DATETIME DEFAULT CURRENT_TIMESTAMP
);

SELECT * FROM TRANSACTIONS;
SELECT * FROM ACCOUNT;
-- 1. Deposit 2000 Rs into John’s account
START TRANSACTION;
UPDATE ACCOUNT SET BALANCE=BALANCE+2000 WHERE ACCOUNTHOLDERNAME='JOHN';
INSERT INTO TRANSACTIONS(FROMACCOUNT, TOACCOUNT,AMOUNT,TRANSACTIONTYPE) VALUES
(NULL, 1,2000,'DEPOSIT');
COMMIT;

-- 2. Withdraw Rs 3000 from Priya’s account
START transaction;
UPDATE ACCOUNT SET BALANCE=BALANCE-3000 WHERE ACCOUNTHOLDERNAME='PRIYA';
INSERT INTO TRANSACTIONS(FROMACCOUNT, TOACCOUNT,AMOUNT,TRANSACTIONTYPE)
VALUES(2,null,3000,'WITHDRAW');
COMMIT;

-- 3. Transfer Rs 1500 from John to Amit
START TRANSACTION;
UPDATE ACCOUNT SET BALANCE=BALANCE-1500 WHERE ACCOUNTHOLDERNAME="JOHN";
UPDATE ACCOUNT SET BALANCE=BALANCE+1500 WHERE ACCOUNTHOLDERNAME="AMIT";
INSERT INTO TRANSACTIONS(FROMACCOUNT, TOACCOUNT,AMOUNT,TRANSACTIONTYPE)
VALUES(1,3,1500,'TRANSFER');
COMMIT;

-- 4. Use SAVEPOINT to partially rollback
START TRANSACTION;
INSERT INTO ACCOUNT(ACCOUNTHOLDERNAME, BALANCE) VALUES("SONALI",50000);
UPDATE ACCOUNT SET BALANCE=BALANCE+1000 WHERE ACCOUNTID=2;
SAVEPOINT S1;
ROLLBACK TO S1;

-- 5. Test Rollback
ROLLBACK;

-- 6. View all transaction history
SELECT * FROM TRANSACTIONS;

-- 7.Show accounts with balance below Rs 5000
SELECT * FROM ACCOUNT WHERE BALANCE < 5000;
  


