DROP FUNCTION IF EXISTS FULLNAME;

DELIMITER //

CREATE FUNCTION FULLNAME(
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50)
)
RETURNS VARCHAR(101)
DETERMINISTIC
BEGIN
    RETURN CONCAT(FIRST_NAME, ' ', LAST_NAME);
END //

DELIMITER ;
SELECT FULLNAME('AISHU','POTABATTI');

-- 3. UDF TO CHECK EVEN NUMBER
DELIMITER //

CREATE FUNCTION CHECK_EVEN(A INT)
RETURNS BOOLEAN
DETERMINISTIC
BEGIN
    IF A%2=0 THEN 
    RETURN TRUE;
    ELSE
		RETURN FALSE;
	END IF;
    
END //

DELIMITER ;
SELECT CHECK_EVEN(3534);

-- 4. UDF TO GET AGE FROM BIRTHDATE
DELIMITER //
CREATE FUNCTION GET_BIRTHDATE(DOB DATE)
RETURNS INT
DETERMINISTIC
BEGIN
	RETURN TIMESTAMPDIFF(YEAR,DOB,CURDATE());
END //
DELIMITER ;
SELECT GET_BIRTHDATE('2004-09-24')

-- 5. UDF TO CALCULATE SIMPLE INTEREST

DELIMITER //

CREATE FUNCTION SIMPLE_INTEREST(
    P DECIMAL(10,2),
    R DECIMAL(5,2),
    T DECIMAL(5,2)
)
RETURNS DECIMAL(10,2)
DETERMINISTIC
BEGIN
    RETURN (P * R * T) / 100;
END //

DELIMITER ;
SELECT SIMPLE_INTEREST(1000, 5, 2);

-- 6. UDF TO CHECK IF STRING IS PALINDROME
DROP FUNCTION IF EXISTS PALINDROME;
DELIMITER //

CREATE FUNCTION PALINDROME(S VARCHAR(100))
RETURNS BOOLEAN
DETERMINISTIC
BEGIN
    IF S = REVERSE(S) THEN
        RETURN TRUE;
    ELSE
        RETURN FALSE;
    END IF;
END //

DELIMITER ;
SHOW CREATE FUNCTION PALINDROME;
SELECT PALINDROME('HELLO');

-- 7. UDF TO CONVERT KILOMETERS TO MILES
DELIMITER //
CREATE FUNCTION KM_MILES(KM DECIMAL(10,2))
RETURNS DECIMAL(10,2)
DETERMINISTIC
BEGIN 
	RETURN KM*0.64532;
END //
DELIMITER ;
SELECT KM_MILES(5.98675)

-- 8. UDF TO GET FIRST LETTER OF NAME CAPITALIZED
DELIMITER //

CREATE FUNCTION GET_CAP(NAME VARCHAR(100))
RETURNS VARCHAR(100)
DETERMINISTIC
BEGIN
    RETURN CONCAT(
        UPPER(LEFT(NAME,1)),
        LOWER(SUBSTRING(NAME,2))
    );
END //

DELIMITER ;
SELECT GET_CAP("word");

-- 9. UDF TO CALCULATE FACTORIAL
DROP FUNCTION IF EXISTS FACTORIAL;
DELIMITER //
CREATE FUNCTION FACTORIAL(N INT)
RETURNS BIGINT
DETERMINISTIC
BEGIN
	DECLARE F BIGINT DEFAULT 1;
    WHILE N>0 DO
		SET F=F*N;
        SET N=N-1;
	END WHILE;
    RETURN F;
END //
DELIMITER ;
SELECT FACTORIAL(5);

-- 10. UDF TO MASK A PHONE NUMBER(E.G., 1234567890-->****7890)
DELIMITER //
CREATE FUNCTION M_PHONE(PHONE VARCHAR(20))
RETURNS VARCHAR(100)
DETERMINISTIC
BEGIN
	RETURN CONCAT(REPEAT('*',LENGTH(PHONE)-4),RIGHT(PHONE,4));
END //
DELIMITER ;
SELECT M_PHONE('1234567890');

-- 11. UDF TO GET DISCOUNT ON PRICE
DELIMITER //
CREATE FUNCTION GET_DISCOUNT(PRICE DECIMAL(10,2), DISCOUNT_PERCENT INT)
RETURNS DECIMAL(10,2)
DETERMINISTIC
BEGIN 
	DECLARE DISCOUNT_PRICE DECIMAL(10,2);
    SET DISCOUNT_PRICE=PRICE-(PRICE*DISCOUNT_PERCENT/100);
    RETURN DISCOUNT_PRICE;
END //
DELIMITER ;
SELECT GET_DISCOUNT(10000,80);







